apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clickhouse-zookeeper

resources:
  - namespace.yaml
  - zookeeper.yaml

patches:
  - path: patch-disable-istio.yaml
    target:
      kind: StatefulSet
      name: zookeeper
