apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clickhouse-operator

resources:
  - namespace.yaml
  - clickhouse-operator.yaml
  - clickhouse-operator-config.yaml

patches:
  - path: patch-disable-istio.yaml
    target:
      kind: Deployment
      name: clickhouse-operator
